---
diskdetails:
  - device: /dev/sdc
    number: 1
    part_start: 1MiB
    part_end: 4GiB
    path: /part1
    partition: /dev/sdc1
    fstype: xfs
  
  - device: /dev/sdc
    number: 2
    part_start: 4GiB
    part_end: 9GiB
    path: /part2
    partition: /dev/sdc2
    fstype: ext4
...